# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-09 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'fruit_mainshop',
            },
        ),
    ]
